
[otherworlder]
	#How many times will the entity attempt to spawn before failing
	#0 = disabled, 1 = guaranteed, higher = lower chance
	#default = 25
	#Range: 0 ~ 50
	spawnAttempts = 30
	#One of how many chances for Shizu to spawn when an otherworlder spawns.
	#Range: 0 ~ 1024
	shizuChance = 30
	#One of how many chances for Hinata to spawn when an otherworlder spawns.
	#Range: 0 ~ 1024
	hinataChance = 69

[aqua_frog]
	#How many times will the entity attempt to spawn before failing
	#0 = disabled, 1 = guaranteed, higher = lower chance
	#default = 20
	#Range: 0 ~ 50
	spawnAttempts = 20

[armoursaurus]
	#How many times will the entity attempt to spawn before failing
	#0 = disabled, 1 = guaranteed, higher = lower chance
	#default = 5
	#Range: 0 ~ 50
	spawnAttempts = 5

[army_wasp]
	#How many times will the entity attempt to spawn before failing
	#0 = disabled, 1 = guaranteed, higher = lower chance
	#default = 50
	#Range: 0 ~ 50
	spawnAttempts = 50

[barghest]
	#How many times will the entity attempt to spawn before failing
	#0 = disabled, 1 = guaranteed, higher = lower chance
	#default = 10
	#Range: 0 ~ 50
	spawnAttempts = 10

[beast_gnome]
	#How many times will the entity attempt to spawn before failing
	#0 = disabled, 1 = guaranteed, higher = lower chance
	#default = 20
	#Range: 0 ~ 50
	spawnAttempts = 20

[black_spider]
	#How many times will the entity attempt to spawn before failing
	#0 = disabled, 1 = guaranteed, higher = lower chance
	#default = 5
	#Range: 0 ~ 50
	spawnAttempts = 5

[blade_tiger]
	#How many times will the entity attempt to spawn before failing
	#0 = disabled, 1 = guaranteed, higher = lower chance
	#default = 15
	#Range: 0 ~ 50
	spawnAttempts = 15

[bulldeer]
	#How many times will the entity attempt to spawn before failing
	#0 = disabled, 1 = guaranteed, higher = lower chance
	#default = 10
	#Range: 0 ~ 50
	spawnAttempts = 10

[direwolf]
	#How many times will the entity attempt to spawn before failing
	#0 = disabled, 1 = guaranteed, higher = lower chance
	#default = 1
	#Range: 0 ~ 50
	spawnAttempts = 1
	#One of how many chances for a Direwolf to be an Alpha.
	#Range: 0 ~ 1024
	alphaWolf = 10
	#One of how many chances for a Tempest Wolf to have the Star birthmark.
	#Range: 0 ~ 1024
	starBirthmark = 8
	#The percentage chance for a direwolf pack to be evolved
	#Range: 0.0 ~ 100.0
	evolvedPack = 30.0
	#The percentage chance for a direwolf pack to be Elemental Fang based on biomes
	#Range: 0.0 ~ 100.0
	elementalPack = 65.0
	#The percentage chance for a direwolf pack to be Tempest Wolves
	#Range: 0.0 ~ 100.0
	tempestPack = 5.0

[dragonPeacock]
	#How many times will the entity attempt to spawn before failing
	#0 = disabled, 1 = guaranteed, higher = lower chance
	#default = 25
	#Range: 0 ~ 50
	spawnAttempts = 25

[evilCentipede]
	#How many times will the entity attempt to spawn before failing
	#0 = disabled, 1 = guaranteed, higher = lower chance
	#default = 30
	#Range: 0 ~ 50
	spawnAttempts = 30

[feathered_serpent]
	#How many times will the entity attempt to spawn before failing
	#0 = disabled, 1 = guaranteed, higher = lower chance
	#default = 60
	#Range: 0 ~ 50
	spawnAttempts = 50

[giantAnt]
	#How many times will the entity attempt to spawn before failing
	#0 = disabled, 1 = guaranteed, higher = lower chance
	#default = 10
	#Range: 0 ~ 50
	spawnAttempts = 10

[giantBat]
	#How many times will the entity attempt to spawn before failing
	#0 = disabled, 1 = guaranteed, higher = lower chance
	#default = 2
	#Range: 0 ~ 50
	spawnAttempts = 2

[giantBear]
	#How many times will the entity attempt to spawn before failing
	#0 = disabled, 1 = guaranteed, higher = lower chance
	#default = 5
	#Range: 0 ~ 50
	spawnAttempts = 5

[giantCod]
	#How many times will the entity attempt to spawn before failing
	#0 = disabled, 1 = guaranteed, higher = lower chance
	#default = 5
	#Range: 0 ~ 50
	spawnAttempts = 5

[giantSalmon]
	#How many times will the entity attempt to spawn before failing
	#0 = disabled, 1 = guaranteed, higher = lower chance
	#default = 5
	#Range: 0 ~ 50
	spawnAttempts = 5

[goblin]
	#How many times will the entity attempt to spawn before failing
	#0 = disabled, 1 = guaranteed, higher = lower chance
	#default = 2
	#Range: 0 ~ 50
	spawnAttempts = 2

[hellCaterpillar]
	#How many times will the entity attempt to spawn before failing
	#0 = disabled, 1 = guaranteed, higher = lower chance
	#default = 5
	#Range: 0 ~ 50
	spawnAttempts = 5

[hellMoth]
	#How many times will the entity attempt to spawn before failing
	#0 = disabled, 1 = guaranteed, higher = lower chance
	#default = 5
	#Range: 0 ~ 50
	spawnAttempts = 5

[hornedBear]
	#How many times will the entity attempt to spawn before failing
	#0 = disabled, 1 = guaranteed, higher = lower chance
	#default = 3
	#Range: 0 ~ 50
	spawnAttempts = 3

[hornedRabbit]
	#How many times will the entity attempt to spawn before failing
	#0 = disabled, 1 = guaranteed, higher = lower chance
	#default = 2
	#Range: 0 ~ 50
	spawnAttempts = 2

[houndDog]
	#How many times will the entity attempt to spawn before failing
	#0 = disabled, 1 = guaranteed, higher = lower chance
	#default = 12
	#Range: 0 ~ 50
	spawnAttempts = 12
	#One of how many chances for a hound dog to have a snake tail.
	#Range: 0 ~ 1024
	snakeChance = 40

[hoverLizard]
	#How many times will the entity attempt to spawn before failing
	#0 = disabled, 1 = guaranteed, higher = lower chance
	#default = 2
	#Range: 0 ~ 50
	spawnAttempts = 2

[knightSpider]
	#How many times will the entity attempt to spawn before failing
	#0 = disabled, 1 = guaranteed, higher = lower chance
	#default = 8
	#Range: 0 ~ 50
	spawnAttempts = 8

[landfish]
	#How many times will the entity attempt to spawn before failing
	#0 = disabled, 1 = guaranteed, higher = lower chance
	#default = 5
	#Range: 0 ~ 50
	spawnAttempts = 5

[leechLizard]
	#How many times will the entity attempt to spawn before failing
	#0 = disabled, 1 = guaranteed, higher = lower chance
	#default = 8
	#Range: 0 ~ 50
	spawnAttempts = 8

[lizardman]
	#How many times will the entity attempt to spawn before failing
	#0 = disabled, 1 = guaranteed, higher = lower chance
	#default = 2
	#Range: 0 ~ 50
	spawnAttempts = 2

[megalodon]
	#How many times will the entity attempt to spawn before failing
	#0 = disabled, 1 = guaranteed, higher = lower chance
	#default = 10
	#Range: 0 ~ 50
	spawnAttempts = 10

[oneEyedOwl]
	#How many times will the entity attempt to spawn before failing
	#0 = disabled, 1 = guaranteed, higher = lower chance
	#default = 15
	#Range: 0 ~ 50
	spawnAttempts = 15

[orc]
	#How many times will the entity attempt to spawn before failing
	#0 = disabled, 1 = guaranteed, higher = lower chance
	#default = 5
	#Range: 0 ~ 50
	spawnAttempts = 5
	#One of how many chances for an Orc Lord to spawn when an orc spawns.
	#Range: 0 ~ 1024
	lordChance = 1000
	#One of how many chances for an Orc to be an Royal Orc.
	#Range: 0 ~ 1024
	royalChance = 100
	#One of how many chances for a Royal Orc to have Self-Regeneration.
	#Range: 0 ~ 1024
	royalLordChance = 8

[salamander]
	#How many times will the entity attempt to spawn before failing
	#0 = disabled, 1 = guaranteed, higher = lower chance
	#default = 10
	#Range: 0 ~ 50
	spawnAttempts = 10

[sissie]
	#How many times will the entity attempt to spawn before failing
	#0 = disabled, 1 = guaranteed, higher = lower chance
	#default = 20
	#Range: 0 ~ 50
	spawnAttempts = 20

[slime]
	#How many times will the entity attempt to spawn before failing
	#0 = disabled, 1 = guaranteed, higher = lower chance
	#default = 10
	#Range: 0 ~ 50
	spawnAttempts = 10
	#One of how many chances for a metal slime to spawn when a slime spawns.
	#Range: 0 ~ 1024
	metalChance = 500
	#One of how many chances for a supermassive slime to spawn when a slime spawns.
	#Range: 0 ~ 1024
	supermassiveChance = 1000

[spearToro]
	#How many times will the entity attempt to spawn before failing
	#0 = disabled, 1 = guaranteed, higher = lower chance
	#default = 30
	#Range: 0 ~ 50
	spawnAttempts = 30

[tempestSerpent]
	#How many times will the entity attempt to spawn before failing
	#0 = disabled, 1 = guaranteed, higher = lower chance
	#default = 30
	#Range: 0 ~ 50
	spawnAttempts = 30

[unicorn]
	#How many times will the entity attempt to spawn before failing
	#0 = disabled, 1 = guaranteed, higher = lower chance
	#default = 5
	#Range: 0 ~ 50
	spawnAttempts = 5

[winged_cat]
	#How many times will the entity attempt to spawn before failing
	#0 = disabled, 1 = guaranteed, higher = lower chance
	#default = 40
	#Range: 0 ~ 50
	spawnAttempts = 40

[slimes]
	#Range slimes get aggressive when another slime gets attacked
	#Range: 0 ~ 1024
	awarenessRange = 16

[hellMothsAndCaterpillars]
	#Range hell moths get aggressive when a cocoon/hell caterpillar gets attacked
	#Range: 0 ~ 1024
	awarenessRange = 16

[giantFish]
	#Range giant fish get aggressive when a small version gets attacked
	#Range: 0 ~ 1024
	awarenessRange = 16

